
  CREATE TABLE "OBV6"."SGC001" 
   (	"COMP" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AREA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NOMIND" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"TIPVALM" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"META" FLOAT(126) NOT NULL ENABLE, 
	"RESMET" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECCAM" DATE NOT NULL ENABLE, 
	"TIPVALTI" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TOLINF" FLOAT(126) NOT NULL ENABLE, 
	"FECCATI" DATE NOT NULL ENABLE, 
	"TIPVALTS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TOLSUP" FLOAT(126) NOT NULL ENABLE, 
	"FECCATS" DATE NOT NULL ENABLE, 
	"CALCULO" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"DATOS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROCES" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PERIOD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NIVAPP" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DESCRI" VARCHAR2(75 BYTE) NOT NULL ENABLE, 
	"ESTATU" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"VIGENC" DATE NOT NULL ENABLE, 
	"COMPOR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECCRE" DATE NOT NULL ENABLE, 
	"USRACT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECACT" DATE NOT NULL ENABLE, 
	"INSTANCIA" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("COMP", "AREA", "CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
