
  CREATE TABLE "OBV6"."SGC001D" 
   (	"COMP" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AREA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NOMIND" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CALCULO" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"DATOS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROCES" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PERIOD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NIVAPP" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DESCRI" VARCHAR2(75 BYTE) NOT NULL ENABLE, 
	"ESTATU" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"VIGENC" DATE NOT NULL ENABLE, 
	"COMPOR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECCRE" DATE NOT NULL ENABLE, 
	"INSTANCIA" NUMBER(*,0) NOT NULL ENABLE, 
	"REGIST" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "OBV6"."SGC001D_TRG" 
BEFORE INSERT ON SGC001D 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.REGIST IS NULL THEN
      SELECT SGC001D_SEQ.NEXTVAL INTO :NEW.REGIST FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "OBV6"."SGC001D_TRG" ENABLE;
