
  CREATE TABLE "OPENBIZVIEW"."CST005" 
   (	"CENTRO" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"ORDEN" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECCRE" DATE NOT NULL ENABLE, 
	"USRACT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECACT" DATE NOT NULL ENABLE, 
	"INSTANCIA" NUMBER(*,0) NOT NULL ENABLE);