create or replace FUNCTION COUNT_INDH06 (PBUSQUEDA VARCHAR2, PCODCIA VARCHAR2, PCODUBI VARCHAR2, PANOCAL INTEGER, PSEMCAL INTEGER, PINSTANCIA INTEGER)
RETURN NUMBER AS
VCOUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO VCOUNT 
FROM INDH06
WHERE CODCIA||CODUBI||ANOCAL||SEMCAL LIKE '%'||PBUSQUEDA||'%'
AND CODCIA LIKE PCODCIA||'%' 
AND CODUBI LIKE PCODUBI||'%'
AND TO_CHAR(ANOCAL) LIKE PANOCAL||'%'
AND TO_CHAR(SEMCAL) LIKE PSEMCAL||'%' 
AND INSTANCIA = PINSTANCIA;
RETURN VCOUNT;
END;